version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12
    build:
        commands:
        - echo "Bucket name is ${S3BUCKET_ADMIN} and Stack name is ${STACKNAME}"
        - aws cloudformation describe-stacks --region eu-central-1 --stack-name ${STACKNAME} > ./frontend/stackinfo.json
        - cd ./frontend
        - npm run update-env
        - npm install aws-sdk
        - npm run initial-config
        - npm install
        - npm install -g @angular/cli
        - npm run build
        - cd ..
    post_build:
        commands:
        - aws s3 sync --delete frontend/dist/aws-serverless-cms s3://${S3BUCKET_ADMIN}/scms --cache-control max-age=3600 --acl public-read
